Module modQryInvDes

    Public qrySqlInvAlmDesImp As String = "SELECT * FROM TEMPORAL_IMPRESION_DESPACHOS"

    Public delSqlInvAlmDesImp As String = "DELETE FROM TEMPORAL_IMPRESION_DESPACHOS"

    Public intSqlInvAlmDesImp As String = " INSERT INTO TEMPORAL_IMPRESION_DESPACHOS VALUES(@ID_TEMP_IMP_DESPACHO, @ID_DESPACHO, @FECHA_DESPACHO, @ID_PEDIDO, " +
" @FECHA_PEDIDO, @ID_CLIENTE, @SOLICITANTE,  @CONFIRMADO, @DIRECCION_1, @DIRECCION_2, @NUM_LINEA, @ID_PRODUCTO, @NOMBRE_PRODUCTO, @CANTIDAD, @UM, @MEMO) "

End Module
