Module modQryPresupuesto

    Public qry4dPrePri As String = "SELECT  CONCAT(CONCAT(CONCAT(CONCAT(CON.Codigo_Cuenta_Contable,'-'), CON1.__DISPONIBLE3),'-'),CON.Empresa) AS ID_PRESUPUESTO," +
         "CONCAT(CONCAT(CON.Codigo_Cuenta_Contable,'-'), CON.Empresa) AS ID_CUENTA,CON1.__DISPONIBLE3 AS ID_DEPARTAMENTO,CON.Empresa AS ID_EMPRESA," +
         "CON.Nombre_Cuenta_Contable," +
         "CON.PRESUPUESTO1_MES1 AS PRESUPUESTO_ENERO, " +
         "CON.PRESUPUESTO1_MES2 AS PRESUPUESTO_FEBRERO, CON.PRESUPUESTO1_MES3 AS PRESUPUESTO_MARZO, " +
         "CON.PRESUPUESTO1_MES4 AS PRESUPUESTO_ABRIL, CON.PRESUPUESTO1_MES5  AS PRESUPUESTO_MAYO," +
         "CON.PRESUPUESTO1_MES6 AS PRESUPUESTO_JUNIO, CON.PRESUPUESTO1_MES7 AS PRESUPUESTO_JULIO," +
         "CON.PRESUPUESTO1_MES8 AS PRESUPUESTO_AGOSTO, CON.PRESUPUESTO1_MES9 AS PRESUPUESTO_SEPTIEMBRE," +
         "CON.PRESUPUESTO1_MES10 AS PRESUPUESTO_OCTUBRE, CON.PRESUPUESTO1_MES11  AS PRESUPUESTO_NOVIEMBRE, " +
         "CON.PRESUPUESTO1_MES12 AS PRESUPUESTO_DICIEMBRE,CURRENT_DATE ( ) AS FECHA_MOD FROM CONT_Presupuesto_Detalle CON, " +
         "CONT_Presupuesto_Principal CON1 WHERE CON.Codigo_Presupuesto_Empresa = CON1.CODIGO_PRESUPUESTO_EMPRESA " +
         "AND      (CON.PRESUPUESTO1_MES1 +  " +
"PRESUPUESTO1_MES2 +  PRESUPUESTO1_MES3 +   PRESUPUESTO1_MES4 +  " +
"PRESUPUESTO1_MES5 +  PRESUPUESTO1_MES6 +   PRESUPUESTO1_MES7 +  " +
"PRESUPUESTO1_MES8 +  PRESUPUESTO1_MES9 +  PRESUPUESTO1_MES10 +  " +
"PRESUPUESTO1_MES11 +  PRESUPUESTO1_MES12) <> 0" +
"AND CON1.ANO_PRESUPUESTO = YEAR  (Current_date()) ;"

    Public qry4dPreApli As String = "SELECT   CONCAT(CONCAT(CONCAT(CONCAT(GL_ACCOUNT_CODE,'-'), DEPARTMENT_CODE), '-'),CORP) AS ID_PRESUPUESTO," +
         " CONCAT(CONCAT(GL_ACCOUNT_CODE,'-'), CORP) AS ID_CUENTA, DEPARTMENT_CODE ID_DEPARTAMENTO, CORP AS ID_EMPRESA," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 1 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_ENERO," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 2 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_FEBRERO," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 3 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_MARZO," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 4 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_ABRIL," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 5 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_MAYO," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 6 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_JUNIO," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 7 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_JULIO," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 8 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_AGOSTO," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 9 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_SEPTIEMBRE," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 10 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_OCTUBRE," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 11 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_NOVIEMBRE," +
         " SUM   (CASE  WHEN MONTH    (POST_TO_DATE) = 12 THEN   CASE WHEN DEBIT_AMOUNT = 0   THEN  -(CREDIT_AMOUNT)   ELSE  DEBIT_AMOUNT END    ELSE 0 END)  AS APLICACION_DICIEMBRE," +
         " CURRENT_DATE ( ) AS FECHA_MOD FROM CONT_Asiento_Detalle WHERE YEAR (POST_TO_DATE) = YEAR  (Current_date())" +
" AND      `GL ACCOUNT TYPE` = 'G'  " +
" AND Confirmado = TRUE" +
" AND GL_ACCOUNT_CODE LIKE '6%' GROUP BY CORP,GL_ACCOUNT_CODE, DEPARTMENT_CODE ORDER BY GL_ACCOUNT_CODE, DEPARTMENT_CODE;"

    Public qry4dPreAplDet As String = "SELECT   CONCAT(CONCAT(CONCAT(CONCAT(CON.GL_ACCOUNT_CODE,'-'), CON.DEPARTMENT_CODE), '-'),CON.CORP)  AS ID_PRESUPUESTO, " +
         "CON.TRANSACTION_ID AS ID_ASIENTO, CON.DOCUMENT_ID AS NUM_ASIENTO, CON.POST_TO_DATE AS FECHA_ASIENTO, " +
         "CONCAT(CONCAT( CON.GL_ACCOUNT_CODE,'-'), CON.CORP) AS ID_CUENTA,  CON.DEBIT_AMOUNT, " +
         "-(CON.CREDIT_AMOUNT)  AS CREDIT_AMOUNT, CON.ADJUSTMENT_TYPE AS TIPO, " +
         "CON.CORP AS ID_EMPRESA, CON.MEMO, CON1.MEMO_2, CON.DEPARTMENT_CODE AS ID_DEPARTAMENTO, " +
         "CON.CURRENCY_CODE AS ID_MONEDA, " +
         "YEAR (CON.POST_TO_DATE)  AS ANIO, " +
         "MONTH (CON.POST_TO_DATE)  AS MES, CURRENT_DATE ( ) AS FECHA_MOD  FROM     CONT_Asiento_Principal CON1, CONT_Asiento_Detalle CON " +
         "WHERE    CON1.TRANSACTION_ID=CON.TRANSACTION_ID AND      YEAR (CON.POST_TO_DATE) = YEAR  (Current_date()) AND      CON.`GL ACCOUNT TYPE` = 'G' " +
         "AND CON.GL_ACCOUNT_CODE LIKE '6%' AND      CON.Confirmado = TRUE;"

    Public qrySqlPrePri As String = "SELECT * FROM PRESUPUESTO"
    Public qrySqlPreApli As String = "SELECT * FROM PRESUPUESTO_APLICADO"
    Public delSqlPrePri As String = "DELETE FROM PRESUPUESTO"
    Public delSqlPreApli As String = "DELETE FROM PRESUPUESTO_APLICADO"
    Public delSqlPreApliDet As String = "DELETE FROM PRESUPUESTO_APLICADO_DETALLE"

    Public intSqlPrePri As String = "INSERT INTO PRESUPUESTO VALUES(@ID_PRESUPUESTO, @ID_CUENTA, @ID_DEPARTAMENTO, @ID_EMPRESA, @NOMBRE_CUENTA_CONTABLE, @PRESUPUESTO_ENERO, @PRESUPUESTO_FEBRERO, " +
"@PRESUPUESTO_MARZO, @PRESUPUESTO_ABRIL, @PRESUPUESTO_MAYO, @PRESUPUESTO_JUNIO, @PRESUPUESTO_JULIO, @PRESUPUESTO_AGOSTO, @PRESUPUESTO_SEPTIEMBRE, @PRESUPUESTO_OCTUBRE, " +
"@PRESUPUESTO_NOVIEMBRE, @PRESUPUESTO_DICIEMBRE, @FECHA_MOD )"
    Public intSqlPreApli As String = "INSERT INTO PRESUPUESTO_APLICADO VALUES(@ID_PRESUPUESTO, @ID_CUENTA, @ID_DEPARTAMENTO, @ID_EMPRESA,	@APLICACION_ENERO,	" +
"@APLICACION_FEBRERO, @APLICACION_MARZO,	@APLICACION_ABRIL,	@APLICACION_MAYO, " +
"@APLICACION_JUNIO,	@APLICACION_JULIO,	@APLICACION_AGOSTO, @APLICACION_SEPTIEMBRE, " +
"@APLICACION_OCTUBRE, @APLICACION_NOVIEMBRE,	@APLICACION_DICIEMBRE, @FECHA_MOD)"
    Public intSqlPreAplDet As String = "INSERT INTO PRESUPUESTO_APLICADO_DETALLE VALUES(@ID_PRESUPUESTO, @ID_ASIENTO, @NUM_ASIENTO, @FECHA_ASIENTO,	@ID_CUENTA,	" +
"@DEBIT_AMOUNT, @CREDIT_AMOUNT,	@TIPO,	@ID_EMPRESA, " +
"@MEMO,	@MEMO_2,	@ID_DEPARTAMENTO, @ID_MONEDA, " +
"@ANIO, @MES, @FECHA_MOD)"

End Module
