Module modQryCliFac

    Public qry4dCliFacPri As String = "SELECT CODIGO_FACTURA AS ID_FACTURA,NUMERO_FACTURA,SerieDocumento AS SERIE,Prefijo_Documento AS PREFIJO, " +
    " NumeroSecuencialDocumento AS FOLIO, " +
    " TIPO_DOCUMENTO_FACT_DEV AS TIPO,CODIGO_CLIENTE AS ID_CLIENTE,FECHA_FACTURA,FECHA_VENCIMIENTO, " +
    " VALOR_FACTURA,SUBTOTAL_CON_IVA AS SUBTOTAL,TOTAL_IMPUESTOS AS IMPUESTO,VALOR_TOTAL_DESCUENTO AS DESCUENTO, " +
    " VALOR_TOTAL_PAGADO AS PAGO,VALOR_TOTAL_SALDO_A_COBRAR AS SALDO,DIA,MES,ANIO, " +
    " CODIGO_MONEDA AS ID_MONEDA, INFO_CREACION,INFO_CONFIRMADO,INFO_ANULADO, " +
    " NUMERO_PEDIDO_SISTEMA AS ID_PEDIDO,ORIGEN AS ID_SUCURSAL, " +
    " CONFIRMADO,ANULADA AS ANULADO,CURRENT_DATE ( ) AS FECHA_MOD " +
    " FROM CLNT_Factura_Principal WHERE TIPO_DOCUMENTO = 'FACT' " +
    " AND EMPRESA = 'CIMSA' AND ANIO >=2017 " +
    " ORDER BY FECHA_FACTURA"

    Public qry4dCliFacDet As String = "SELECT   INV.DOC_ID_CORP2 AS ID_FACTURA, INV.`ORIGIN MEMO`,INV.Posicion AS LINEA, " +
    " INV.PRODUCT_ID AS ID_PRODUCTO, INV.QUANTITY AS CANTIDAD, " +
    " CASE  WHEN INV.QUANTITY = 0 THEN 0 ELSE NET_LINE_TOTAL/QUANTITY END    AS PRECIO_FINAL, " +
    " INV.NET_LINE_TOTAL AS SUBTOTAL, " +
    " INV.Cotizacion_Movimiento AS TIPO_CAMBIO, " +
    " CASE WHEN INV.CURRENCY_TYPE = 'US' THEN NET_LINE_TOTAL*COTIZACION_MOVIMIENTO ELSE NET_LINE_TOTAL  END  AS SUBTOTAL_CONVERT, " +
    " CASE WHEN  CURRENCY_TYPE = 'US' THEN INV.`TAX TOTAL`*COTIZACION_MOVIMIENTO ELSE `TAX TOTAL` END      AS IVA_CONVERT, " +
    " CURRENT_DATE ( ) AS FECHA_MOD " +
    " FROM CLNT_Factura_Principal CLN, INVT_Producto_Movimientos INV " +
    " WHERE CLN.CODIGO_FACTURA=INV.DOC_ID_CORP2 AND CLN.TIPO_DOCUMENTO = 'FACT' " +
    " AND CLN.EMPRESA = 'CIMSA' AND CLN.ANIO >=2017"

    Public qrySqlCliFacPri As String = "SELECT * FROM FACTURAS"
    Public qrySqlCliFacDet As String = "SELECT * FROM FACTURAS_DETALLE"

    Public delSqlCliFacPri As String = "DELETE FROM FACTURAS"
    Public delSqlCliFacDet As String = "DELETE FROM FACTURAS_DETALLE"

    Public intSqlCliFacPri As String = "INSERT INTO FACTURAS VALUES(@ID_FACTURA, @NUMERO_FACTURA, @SERIE, @PREFIJO, @FOLIO, @TIPO, @ID_CLIENTE " +
        " @FECHA_FACTURA, @FECHA_VENCIMIENTO, @VALOR_FACTURA, @SUBTOTAL, @IMPUESTO, @DESCUENTO, @PAGO, @SALDO, @DIA, @MES, @ANIO, @ID_MONEDA " +
        " @INFO_CREACION, @INFO_CONFIRMADO, @INFO_ANULADO, @ID_PEDIDO, @ID_SUCURSAL, @CONFIRMADO, @ANULADO, @FECHA_MOD)"
    Public intSqlCliFacDet As String = "INSERT INTO FACTURAS_DETALLE VALUES (@ID_FACTURA, @ORIGEN, @LINEA, @ID_PRODUCTO, @CANTIDAD, @PRECIO_FINAL, " +
        " @SUBTOTAL, @TIPO_CAMBIO, @SUBTOTAL_CONVERT, @IVA_CONVERT, @FECHA_MOD)"

End Module
